## Default values for tyk-pro chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
## See Tyk Helm documentation for installation details:
## https://tyk.io/docs/tyk-self-managed/tyk-helm-chart/
## Registry for all Tyk images - https://hub.docker.com/u/tykio

dash:
  # The hostname to bind the Dashboard to.
  hostName: tyk-dashboard.local
  # If set to true the Dashboard will use SSL connection.
  # You will also need to set the:
  # - TYK_DB_SERVEROPTIONS_CERTIFICATE_CERTFILE
  # - TYK_DB_SERVEROPTIONS_CERTIFICATE_KEYFILE
  # variables in extraEnvs object array to define your SSL cert and key files.
  tls: false
  org:
    # The hostname to bind the Portal to.
    cname: tyk-portal.local
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - tyk-dashboard.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.ingress

portal:
  path: /
  # Creates an ingress object in k8s. Will require an ingress-controller and
  # annotation to that ingress controller.
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - tyk-portal.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.ingress

gateway:
  # The hostname to bind the Gateway to.
  hostName: tyk-gw.local
  # When true, sets the gateway protocol to HTTPS.
  tls: false
  # Creates an ingress object in k8s. Will require an ingress-controller and
  # annotation to that ingress controller.
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - tyk-gw.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.ingress
