---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: authtoken
spec:
  name: Auth Token
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin/
    strip_listen_path: true
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization

---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authtoken
spec:
  name: AuthToken Security Policy
  state: active
  active: true
  access_rights_array:
    - name: authtoken
      namespace: default
      versions:
        - Default
